#! /usr/bin/env python3

from hashlib import sha1
from os import mkdir
from pathlib import Path
from shutil import which
from subprocess import PIPE, run, Popen
from sys import stderr, exit

JAR_URL = "https://piston-data.mojang.com/v1/objects/8399e1211e95faa421c1507b322dbeae86d604df/server.jar"
JAR_SHA1 = "8399e1211e95faa421c1507b322dbeae86d604df"

print("ensuring server directory exists...")
if not Path("server").is_dir():
    mkdir("server")

print("checking for server.jar...")
if not Path("server/server.jar").is_file():
    print("server/server.jar not found... fetching server")
    run([which("curl"), JAR_URL, "-o", "server/server.jar"])
else:
    print("server.jar found. validating...")

sha1sum = sha1()
with open("server/server.jar", "rb") as f:
    block = f.read(2**16)
    while len(block) != 0:
        sha1sum.update(block)
        block = f.read(2**16)

if sha1sum.hexdigest() != JAR_SHA1:
    print("could not verify integrity of server.jar... exiting...", file=stderr)
    exit(1)

print("ensuring configuration files...")
with open("server/eula.txt", "w") as f:
    f.writelines(["eula=true"])

with open("server/server.properties", "w") as f, open(
    "resources/server.properties", "r"
) as source:
    f.write(source.read())

print("starting server...")
process = Popen(
    [which("java"), "-Xmx1G", "-jar", "server.jar", "nogui"],
    cwd="./server",
    stdin=PIPE,
    stdout=PIPE,
    stderr=PIPE,
    text=True,
)

for line in process.stdout:
    print(f"server log: {line}", end="")
    if "RCON running on 0.0.0.0:25575" in line:
        print("server RCON is ready, starting tests")
        break

run([which("cargo"), "test", "--", "--test-threads", "1", "--show-output"])

process.kill()
